### ISSUE TITLE
Vector of Min_max values Ordered pairs of subarray of a sequence

### ISSUE THREAD

**Issue by HKRcodes** [rexxyz/language-Programming#97]
Using this code, you can read a sequence of numbers and find the ordered pair (minimum value in subarray, maximum value in subarray) for the subarrays having user given size within the sequence length. We will get a vector having these ordered pairs.
Each new subarray is considered by releasing the first element in the previous subarray and taking in the next element after the previous subarray.

harikrishnanus2002@gmail.com

**Comment by rexxyz** [comment]
thanks fot your contribute
